language: python
python:
  - "3.8.12"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U codecov
  - pip install -U pytest-cov
install:
  - pip install -e .
script:
  pytest --cov=msvc/src msvc/tests
after_success:
  - codecov
