matrix:
  fast_finish: true
  include:
      name: MSVC
      language: python
      python: "3.8.12"
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set changeps1 no
        - conda update -q conda -c conda-forge -y
        - conda env create -f environment.yml
        - conda activate msvc_env
      install:
        - python -m pip install -e .
        - conda install codecov pytest pytest-cov pytest-mpl -c conda-forge -y
      script:
        - python --version
        - python -m pytest --cov=msvc/src msvc/tests --mpl
      after_success:
        - codecov
        - deactivate
