fleet_script_tasks:
  script: &ref_1
    - python --version
    - python -m pytest --cov=msvc/src msvc/tests --mpl
fleet_install_tasks:
  install: &ref_0
    - pip install -U pytest
    - pip install -U codecov
    - pip install -U pytest-cov
    - pip install -U pytest-mpl
matrix:
  fast_finish: true
  include:
    - name: Python 3.8 on Windows
      os: windows
      language: shell
      env:
        - 'PATH=/c/Python38:/c/Python38/Scripts:$PATH'
      python:
        - "3.8.12"
      before_install:
        - choco install python3 --version=3.8.10
        - python -m pip install --upgrade pip wheel
        - export MINICONDA_PATH=$HOME/miniconda;
        - export MINICONDA_PATH_WIN=`cygpath --windows $MINICONDA_PATH`;
        - export MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;
        - export MINICONDA_LIB_BIN_PATH=$MINICONDA_PATH/Library/bin;
        - choco install openssl.light;
        - choco install miniconda3 --params="'/JustMe /AddToPath:1 /D:$MINICONDA_PATH_WIN'";
        - export FFMPEG_PATH=$HOME/ffmpeg/bin;
        - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$MINICONDA_LIB_BIN_PATH:$FFMPEG_PATH:$PATH:$(pwd)";
        - source $MINICONDA_PATH/etc/profile.d/conda.sh;
        - hash -r;
        - conda update conda -c conda-forge -y
        - conda env create -f environment.yml
        - conda activate msvc_env
        - conda install python=3.8.12 -c conda-forge -y
        - conda install -c pytorch-nightly -c conda-forge torchaudio=0.11.0.* -y
      install: *ref_0
      script: *ref_1
      after_success:
        - codecov
        - deactivate
