fleet_script_tasks:
  script: &ref_1
    - python --version
    - python -m pytest --cov=msvc/src msvc/tests --mpl
fleet_install_tasks:
  install: &ref_0
    - pip install -e .
matrix:
  fast_finish: true
  include:
    - name: Python 3.8.12 on Windows
      os: windows
      language: shell
      env:
        - 'PATH=/c/Python38:/c/Python38/Scripts:$PATH'
      python:
        - "3.8.12"
      before_install:
        - choco install python3
        - python -m pip install --upgrade pip wheel
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      install: *ref_0
      script: *ref_1
      after_success:
        - codecov
        - deactivate
