matrix:
  fast_finish: true
  include:
    - name: MSVC
      language: python
      python:
        - "3.8.12"
      before_install:
        - conda activate base
        - conda update conda -c conda-forge -y
        - conda remove --name msvc_env --all -y
        - conda env create -f environment.yml
        - conda activate msvc_env
        - conda install codecov pytest pytest-cov pytest-mpl -c conda-forge -y
      install: pip install -e .
      script:
        - python --version
        - python -m pytest --cov=msvc/src msvc/tests --mpl
      after_success:
        - codecov
        - deactivate
