language: python
python:
  - "3.8.12"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U codecov
  - pip install -U pytest-cov
  - pip install -U pytest-mpl
install:
  - pip install -e .
script:
  python -m pytest --cov=msvc/src msvc/tests --mpl
after_success:
  - codecov
