matrix:
  fast_finish: true
  include:
    - name: MSVC
      language: python
      python:
        - "3.8.12"
      before_install:
        - pip install -r requirements.txt
        - pip install -U codecov pytest pytest-cov pytest-mpl
      install: pip install -e .
      script:
        - python --version
        - python -m pytest --cov=msvc/src msvc/tests --mpl
      after_success:
        - codecov
        - deactivate
